### ISSUE TITLE
Modular data trasport layer.

### ISSUE THREAD

**Issue by alspore** [Tribex/iBrows#2]
For a while now I've been thinking about wrapping html transfer protocols using existing node libraries for use in an electron browser.  This way you could load data from services like tor, i2p, or even a rest api asynchronously without switching browsers.

Your browser seems like a super simple framework for doing that kind of thing so I think I'm gonna hack around with it a bit.  Feel free to join in if you're interested :)

**Comment by JoshTheDerf** [comment]
Huh! That sounds rather interesting! I'd be happy to help/contribute, though Tor is not functional where I live (China), at least not easily.

I wonder if an extension could implement a bittorrent client through this method as well...

**Comment by alspore** [comment]
I've been thinking about that too. It would be cool if one of the transport modules downloaded offline web apps. Each client could seed the torrent.

**Comment by JoshTheDerf** [comment]
For now though, I should probably focus on getting the basic browser features working and implemented sanely. It's a total mess right now, and I wasn't intending on fixing it. xD

Not a lot of free time at the moment, preparing to move back to the U.S. in a couple weeks.

Another long-term goal would be implementing the basic Chrome extension/WebExtension APIs.
